### ISSUE TITLE
Umbrella: Repository Content (Scope)/ TODOs

### ISSUE THREAD

**Issue by simonsan** [rust-unofficial/patterns#116]
Collection of design patterns and the corresponding issues if not contained in the repository already (in reference to Design patterns (by Gamma, Helm, Johnson, Vlissides)). Some patterns are probably not applicable to/realizable with Rust as they stem from OOP, but we'll sort that out on the way.

But in general I think it is also nice to have `design patterns` listed somewhere on a page that are not applicable to Rust and stated why and with an added workaround if any.

```
Checkmark = already existing in repository (link to file)
No checkmark = Link to corresponding issue
No checkmark and no link = Check if applicable for Rust
```

# Coverage

### Creational Patterns

  - [X] [Builder](https://github.com/rust-unofficial/patterns/blob/master/patterns/creational/builder.md)
  - [ ] [Abstract factory](https://github.com/rust-unofficial/patterns/issues/225)
  - [ ] [Factory Method](https://github.com/rust-unofficial/patterns/issues/224)
  - [ ] [Singleton](https://github.com/rust-unofficial/patterns/issues/226)
  - [ ] [Prototype](https://github.com/rust-unofficial/patterns/issues/232)

### Structural Patterns

  - [ ] [Facade](https://github.com/rust-unofficial/patterns/issues/59)
  - [ ] [Adapter](https://github.com/rust-unofficial/patterns/issues/221)
  - [ ] [Decorator](https://github.com/rust-unofficial/patterns/issues/222)
  - [ ] [Proxy](https://github.com/rust-unofficial/patterns/issues/223)
  - [ ] [Bridge](https://github.com/rust-unofficial/patterns/issues/231)
  - [ ] [Composite](https://github.com/rust-unofficial/patterns/issues/230)
  - [ ] Flyweight

### Behavioural Patterns

  - [X] [Interpreter](https://github.com/rust-unofficial/patterns/blob/master/patterns/behavioural/interpreter.md)
  - [X] [Strategy](https://github.com/rust-unofficial/patterns/blob/master/patterns/behavioural/strategy.md)
  - [X] [Visitor](https://github.com/rust-unofficial/patterns/blob/master/patterns/behavioural/visitor.md)
  - [X] [Command](https://github.com/rust-unofficial/patterns/blob/master/patterns/behavioural/command.md) 
  - [ ] [Observer](https://github.com/rust-unofficial/patterns/issues/60)
  - [ ] [Chain of Responsibility](https://github.com/rust-unofficial/patterns/issues/220)
  - [ ] [Iterator](https://github.com/rust-unofficial/patterns/issues/229)
  - [ ] [State](https://github.com/rust-unofficial/patterns/issues/227)
  - [ ] [Mediator](https://github.com/rust-unofficial/patterns/issues/233)
  - [ ] [Memento](https://github.com/rust-unofficial/patterns/issues/234)
  - [ ] Template Method

### Still Uncategorized

- [ ] [WIP] [Typestates/Session types](https://github.com/rust-unofficial/patterns/pull/100)
- [ ] [Entry API](https://github.com/rust-unofficial/patterns/blob/e3ed5133461a3acd26e4ee44a0cdff9a494166e8/patterns/entry.md)
- [ ] [Late bound bounds](https://github.com/rust-unofficial/patterns/blob/e3ed5133461a3acd26e4ee44a0cdff9a494166e8/patterns/late-bounds.md)
- [ ] [Graphs](https://github.com/rust-unofficial/patterns/issues/202)
- [ ] [Platform-specific sub-modules](https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md#platform-specific-opt-in)
- [ ] [Destructor bombs (ensure linear typing dynamically](https://github.com/Munksgaard/session-types/commit/0f25ccb7c3bc9f65fa8eaf538233e8fe344a189a)
- [ ] [Convertible to Foo trait for more generic generics](http://static.rust-lang.org/doc/master/std/fs/struct.File.html#method.open)
- [ ] Iterators (to safely avoid bounds checks)
- [ ] Closures and lifetimes (coupling to lifetime)
- [ ] [Module organisation](https://github.com/rust-unofficial/patterns/issues/212)
  by looking at examples such as Rusts `libstd`, and how it integrated into the Rusts source code, lessons can be learned about ergonomic project management and API design. Closely assosciated with platform-specific sub-modules
- [ ] Extension traits
- [ ] 'Shadow' borrowed version of struct - e.g., double buffering, Niko's parser generator
- [ ] Composition of structs to please the borrow checker
- [ ] `Error` traits and `Result` forwarding

## Idioms

- [ ] [Trait to separate visibility of methods from visibility of data](https://github.com/sfackler/rust-postgres/blob/v0.9.6/src/lib.rs#L1400)
- [ ] Stability for extensibility
- [ ] Leak amplification 
  "Vec::drain sets the Vec's len to 0 prematurely so that mem::forgetting Drain "only" mem::forgets more stuff. instead of exposing uninitialized memory or having to update the len on every iteration"
- [ ] Interior mutability - UnsafeCell, Cell, RefCell

## Anti-patterns

- [ ] [WIP] [Thread + catch_panic for exceptions](https://github.com/rust-unofficial/patterns/pull/109)
- [ ] [WIP] [Clone to satisfy the borrow checker](https://github.com/rust-unofficial/patterns/pull/110)
- [ ] Matching all fields of a struct (back compat)
- [ ] Wildcard matches
- [ ] Taking an enum rather than having multiple functions
- [ ] `Unwrap()`ing every `Result` instead of forwarding it

## Functional Programming
- [ ] Currying (from #117)
- [ ] Higher-order functions (from #117)
- [ ] Collections (from #117)

## Refactoring
- [ ] Refactoring from `unwrap` to `Result`

## General Unsorted

- [ ] Public type aliases
- [ ] Use conversion traits
- [ ] Laziness: Use Iterators
- [ ] Laziness: Take closures
- [ ] Custom traits for input parameters
- [ ] Extension traits

## Notes

- #35: I recently started collecting some API design patterns [here](https://scribbles.pascalhertleif.de/elegant-apis-in-rust.html). I'm not sure if these match what this repo is all about (or which ones you already cover), but I just wanted to say: Feel free to take anything you like from that post! :) 
  The markdown source of that post is [here](https://github.com/killercup/scribbles/blob/gh-pages/_posts/2016-07-21-elegant-apis-in-rust.md) and I hereby relicense the content as MPL2 (in addition to CC-BY) and allow you to use it in this repo.

### [From Reddit](https://www.reddit.com/r/rust/comments/1bn8s72/share_rust_design_patterns/)

<ul>
      <li>
    <p>
    <a class="relative pointer-events-auto" href="https://cglab.ca/~abeinges/blah/everyone-poops/" rel="noopener nofollow ugc" target="_blank">Pre-Pooping Your Pants</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://smallcultfollowing.com/babysteps/blog/2018/04/16/rust-pattern-rooting-an-rc-handle/" rel="noopener nofollow ugc" target="_blank">Rooting an Rc handle</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://smallcultfollowing.com/babysteps/blog/2018/04/24/rust-pattern-precise-closure-capture-clauses/" rel="noopener nofollow ugc" target="_blank">Precise closure capture clauses</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://smallcultfollowing.com/babysteps/blog/2018/09/02/rust-pattern-iterating-an-over-a-rc-vec-t/" rel="noopener nofollow ugc" target="_blank">Iterating an over a Rc&lt;Vec&lt;T&gt;&gt;</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://users.rust-lang.org/t/blog-post-series-rust-patterns/20080/10" rel="noopener nofollow ugc" target="_blank">https://users.rust-lang.org/t/blog-post-series-rust-patterns/20080/10</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2023/11/15/push-ifs-up-and-fors-down.html" rel="noopener nofollow ugc" target="_blank">Push Ifs Up And Fors Down</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2022/11/18/if-a-tree-falls-in-a-forest-does-it-overflow-the-stack.html" rel="noopener nofollow ugc" target="_blank">If a Tree Falls in a Forest, Does It Overflow the Stack?</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://ismailmaj.github.io/destructing-trees-safely-and-cheaply" rel="noopener nofollow ugc" target="_blank">Destructing trees safely and cheaply</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2022/05/29/builder-lite.html" rel="noopener nofollow ugc" target="_blank">Builder Lite</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2022/06/11/caches-in-rust.html" rel="noopener nofollow ugc" target="_blank">Caches In Rust</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2021/07/09/inline-in-rust.html" rel="noopener nofollow ugc" target="_blank">Inline In Rust</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2018/06/04/newtype-index-pattern.html" rel="noopener nofollow ugc" target="_blank">Newtype Index Pattern</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2018/05/24/typed-key-pattern.html" rel="noopener nofollow ugc" target="_blank">Typed Key Pattern</a>
  </p>
  </li><li>
    <p>
    <a class="relative pointer-events-auto" href="https://matklad.github.io/2018/05/04/encapsulating-lifetime-of-the-field.html" rel="noopener nofollow ugc" target="_blank">Encapsulating Lifetime of the Field</a>
  </p>
  </li>
    </ul>

- [Break on named blocks](https://symbolica.io/posts/control_flow_patterns/#block-breaks)

- [Temporarily opt-in to shared mutation](https://ryhl.io/blog/temporary-shared-mutation/)

- [Actors with Tokio](https://ryhl.io/blog/actors-with-tokio/)

**Comment by burdges** [comment]
I donno if relevant but one can simulate a reasonable degree of simple local inheritance without overloading by using inherent methods on a parent types whose subtrypes are specified using type parameters https://github.com/rust-lang/rfcs/issues/349#issuecomment-733204959 so generic methods on the polymorphic base become available to all children.  In practice, one often needs sealed traits once this gets heavier, so then maybe a true trait interface makes sense, but sometimes the situation is quite simple.

**Comment by fade2black** [comment]
@simonsan  
Strategy pattern: https://medium.com/swlh/strategy-design-pattern-in-rust-5f5486cd294c

**Comment by simonsan** [comment]
> @simonsan
> Strategy pattern: https://medium.com/swlh/strategy-design-pattern-in-rust-5f5486cd294c
> I can add it here.

Nice, for sure! 💯

**Comment by simonsan** [comment]
Today I discovered https://github.com/udoprog/patterns where `game engine patterns` are collected and I was wondering if that might be a good idea to add these patterns in this repository. I opened an issue to discuss this and see what is the general stance on it over at `udoprog/patterns`: https://github.com/udoprog/patterns/issues/1

**Comment by pickfire** [comment]
Something new to addon for cell if anyone work on cell. https://plv.mpi-sws.org/rustbelt/ghostcell/
